import type { ProductDefinition } from "../types"
import {
	Cpu,
	Mail,
	IdCard,
	CircuitBoard,
	FingerprintPattern,
	Shield,
	Grip,
	TrendingUp,
	DatabaseZap,
	HeartPlus,
	Network,
	RefreshCw,
	ScrollText,
	GitFork,
	CircleDollarSign,
	Settings,
	BrickWallShield,
	Shuffle,
	SquareTerminal,
	Server,
	Users,
	Smartphone,
	CreditCard,
	ArrowRightLeft,
	Route,
	Rocket,
	ShieldCheck,
	KeyRound,
	Laptop,
	RefreshCcw,
	Palette,
	Star,
	LogIn,
	Fingerprint,
	HeartPulse,
	Copy,
	Layers,
	Cloud,
	Link,
	Globe,
	Forward,
	Activity,
	Cable,
	UsersRound,
	Lock,
	Plug,
	CloudCog,
	AtSign,
} from "lucide-react"

import Discourse from "../icons/Discourse"
import GitBook from "../icons/GitBook"
import Substack from "../icons/Substack"
import GitHubOutline from "../icons/GitHubOutline"
import Aws from "../icons/Aws"
import Auth0 from "../logos/Auth0"
import Duo from "../logos/Duo"
import GoogleWorkspace from "../logos/GoogleWorkspace"
import JumpCloud from "../logos/JumpCloud"
import MicrosoftEntra from "../logos/MicrosoftEntra"
import Okta from "../logos/Okta"
import OneLogin from "../logos/OneLogin"
import Yubico from "../logos/Yubico"
import Slack from "../logos/Slack"
import FreeRadius from "../logos/FreeRadius"
import Windows from "../logos/Windows"
import Home from "../components/Home"
import Pritunl from "../logos/Pritunl"
import PritunlClient from "../logos/PritunlClient"
import PritunlCloud from "../logos/PritunlCloud"
import PritunlDev from "../logos/PritunlDev"
import AmazonAws from "../logos/AmazonAws"
import GoogleCloud from "../logos/GoogleCloud"
import MicrosoftAzure from "../logos/MicrosoftAzure"
import Hetzner from "../logos/Hetzner"
import Oracle from "../logos/Oracle"

const definition: ProductDefinition = {
	config: {
		name: "Pritunl",
		title: "Pritunl - Enterprise VPN Server",
		description: "Free and open source enterprise VPN server with distributed architecture and scalability.",
		logo: Pritunl,
		logoAlt: "Pritunl",

		navigation: [
			{ name: "Pricing", href: "#pricing" },
			{ name: "Support", href: "#support" },
			{ name: "Documentation", href: "https://docs.pritunl.com/kb/vpn", external: true },
			{ name: "Community Forums", href: "https://forum.pritunl.com", external: true },
		],

		badge: "Open Source Enterprise VPN Server",
		heading: [
			[
				{ text: "Enterprise", highlight: true },
				{ text: " Distributed OpenVPN, WireGuard and IPsec " },
				{ text: "Server", highlight: true },
			],
		],
		subheading: "Virtualize your private networks across datacenters and provide simple remote access in minutes.",

		buttons: [
			{
				label: "Live Demo",
				href: "https://demo.pritunl.com",
				style: "secondary",
				external: true,
			},
			{
				label: "Get Started",
				href: "https://docs.pritunl.com/kb/vpn/getting-started/installation",
				style: "primary",
				external: true,
			},
		],

		featureBlocks: [
			{
				type: "center_open",
				title: "Simple Virtual Private Networks",
				description: "Create a cloud vpn with complex site-to-site links, gateway links and provide local network access to remote users. Protect your network traffic and remote users connecting over public connections with secure encryption. All from a simple web interface.",
				image: "vpn_datacenter",
				imageAlt: "Protected Datacenter",
			},
			{
				type: "logos",
				title: "Multi-Cloud VPC Peering",
				description: "Create multi-cloud WireGuard or IPsec site-to-site links with Pritunl Link. Available for AWS, Google Cloud, Azure, Oracle Cloud, Pritunl Cloud and Hetzner.",
				logoItems: [
					{
						image: AmazonAws,
						imageAlt: "Amazon AWS",
						imageColor: "text-white",
						link: "https://docs.pritunl.com/kb/vpn/link/aws",
						external: true,
					},
					{
						image: GoogleCloud,
						imageAlt: "Google Cloud",
						imageColor: "text-white",
						link: "https://docs.pritunl.com/kb/vpn/link/google-cloud",
						external: true,
					},
					{
						image: MicrosoftAzure,
						imageAlt: "Microsoft Azure",
						link: "https://docs.pritunl.com/kb/vpn/link/azure-link",
						external: true,
					},
					{
						image: Oracle,
						imageAlt: "Oracle Cloud",
						imageColor: "text-[#f80102]",
						link: "https://docs.pritunl.com/kb/vpn/link/oracle-cloud",
						external: true,
					},
					{
						image: PritunlCloud,
						imageAlt: "Pritunl Cloud",
						imageColor: "text-white",
						link: "https://cloud.pritunl.com",
						external: true,
					},
					{
						image: Hetzner,
						imageAlt: "Hetzner",
						imageColor: "text-[#d50c2d]",
						link: "https://www.hetzner.com",
						external: true,
					},
				],
			},
			{
				type: "two_columns",
				title: "The Most Secure VPN Server",
				description: "Pritunl provides innovative security features not available from any other provider. Including TPM and Apple Secure Enclave device authentication, a dynamic firewall, SELinux policies, dual web server design and self shutdown notification system.",
				link: "https://docs.pritunl.com/kb/vpn/security/features",
				linkLabel: "Explore Security Features",
				linkIcon: Cpu,
				cardItems: [
					{
						icon: Cpu,
						title: "Platform and Device Support",
						description: "Pritunl supports all OpenVPN clients. Use the Pritunl Client on macOS, Windows and Linux for full functionality with support for both OpenVPN and WireGuard. Support for Chrome OS OpenVPN profiles also available.",
						link: "https://client.pritunl.com",
						linkLabel: "Pritunl Client Overview",
						external: true,
					},
					{
						icon: Aws,
						title: "AWS VPN Server",
						description: "Interconnect AWS VPC networks across AWS regions and provide reliable remote access with automatic failover that can scale horizontally.",
						link: "/vpc",
						linkLabel: "Explore AWS Integration",
					},
					{
						icon: IdCard,
						title: "Single Sign-On",
						description: "Securely deploy remote access to thousands of users using their existing company account with support for several single sign-on providers and protocols.",
						link: "/sso",
						linkLabel: "See All Supported Providers",
					},
					{
						icon: CircuitBoard,
						title: "Plugin System",
						description: "Highly customizable Python plugin system to allow expanding and modifying Pritunl. Plugins can be created to support custom authentication systems and custom access control systems.",
						link: "https://docs.pritunl.com/kb/vpn/system/plugins",
						linkLabel: "Learn More About Plugins",
						external: true,
					},
				],
			},
			{
				type: "left",
				title: "Distributed and Scalable",
				image: "vpn_servers",
				imageAlt: "Pritunl Distributed Cluster",
				imageNoRing: true,
				items: [
					{
						icon: TrendingUp,
						title: "Scale Easily",
						description: "Pritunl servers can be easily distributed across multiple servers and different datacenters for improved performance, high availability and automatic failover when an instance fails.",
					},
					{
						icon: DatabaseZap,
						title: "Simple Distribution",
						description: "All server communication and interconnecting is done with MongoDB allowing servers to be quickly connected without having to modify firewalls for inter-server communication.",
					},
					{
						icon: HeartPlus,
						title: "High Availability",
						description: "All Pritunl servers are equal in the cluster and can run independently in the event of other instances failing.",
					},
				],
			},
			{
				type: "grid",
				title: "Self Hosted and Reliable",
				description: "A self hosted VPN platform with over 10 years of proven reliability and security, trusted by thousands of organizations worldwide.",
				gridItems: [
					{
						title: "Open Source",
						description: "All source code for Pritunl is publicly available on GitHub, allowing for complete transparency, community contributions and full customization to fit your environment.",
						icon: GitFork,
					},
					{
						title: "Free to Use",
						description: "Free and open source alternative to commercial VPN products such as Aviatrix, Pulse Secure and AnyConnect. Get started immediately with no registration or credit card required.",
						icon: CircleDollarSign,
					},
					{
						title: "Easy Configuration",
						description: "Manage users, servers and organizations from an intuitive web interface. Quickly handle complex multi-server configurations and large deployments without touching config files.",
						icon: Settings,
					},
					{
						title: "Security",
						description: "All traffic between clients and servers is encrypted. Support for two-step authentication with TOTP, push notifications and device authentication using TPM and Secure Enclave.",
						icon: BrickWallShield,
					},
					{
						title: "Multiple Protocols",
						description: "Support for both OpenVPN and WireGuard client connections. WireGuard and IPsec are used for high performance site-to-site links and VPC peering between datacenters.",
						icon: Shuffle,
					},
					{
						title: "REST API",
						description: "Fully integrate Pritunl into your existing infrastructure and CI/CD pipelines using the REST API. Automate user provisioning, server management and configuration changes.",
						icon: SquareTerminal,
					},
				],
			},
			{
				type: "right",
				title: "Connect Infrastructure",
				description: "Provide secure remote access to your corporate infrastructure for users across your organization and interconnect sites.",
				image: "vpn_infrastructure",
				imageAlt: "High Availability Infrastructure",
				imageNoRing: true,
				items: [
					{
						icon: Network,
						title: "WireGuard and IPsec Links",
						description: "Create high performance site-to-site links between datacenters and on-premise networks using WireGuard and IPsec with support for both hub-and-spoke and mesh topologies.",
					},
					{
						icon: RefreshCw,
						title: "Replication and Automated Failover",
						description: "All servers in the cluster operate as equal peers with no single point of failure. When an instance fails, connected clients are automatically routed to a healthy node with no manual intervention.",
					},
					{
						icon: ScrollText,
						title: "Advanced Auditing",
						description: "Capture detailed audit events in structured JSON format for integration with SIEM systems. Track user connections, authentication events and configuration changes across the entire cluster.",
					},
				],
			},
			{
				type: "grid",
				title: "Open Source Alternative",
				description: "Pritunl is the best open source alternative to proprietary commercial vpn products such as Aviatrix,  Ivanti Secure Accese, Pulse Secure and AnyConnect. Create larger cloud vpn networks supporting thousands of concurrent users and get more control over your vpn server without any per-user pricing.",
				link: "https://github.com/pritunl/pritunl",
				linkLabel: "Explore GitHub Repository",
				linkIcon: GitHubOutline,
				gridItems: [
					{
						title: "Ivanti Secure Access Alternative",
						description: "Lower cost and more customizable alternative to Ivanti Secure Access with transparent pricing.",
						icon: FingerprintPattern,
					},
					{
						title: "OpenVPN Access Server Alternative",
						description: "Open source low cost alternative to OpenVPN Access Server with no per-user pricing.",
						icon: Shield,
					},
					{
						title: "Tailscale Alternative",
						description: "Lower cost and more customizable WireGuard server alternative to Tailscale.",
						icon: Grip,
					},
				],
			},
			{
				type: "logos",
				title: "Single Sign-On",
				description: "Securely deploy remote access to thousands of users using their existing company account with support for several single sign-on providers and protocols.",
				logoItems: [
					{
						image: GoogleWorkspace,
						imageAlt: "Google Workspace",
						imageColor: "text-white",
						link: "https://workspace.google.com",
						external: true,
					},
					{
						image: Okta,
						imageAlt: "Okta",
						imageColor: "text-white",
						link: "https://okta.com",
						external: true,
					},
					{
						image: OneLogin,
						imageAlt: "OneLogin",
						imageColor: "text-white",
						link: "https://onelogin.com",
						external: true,
					},
					{
						image: MicrosoftEntra,
						imageAlt: "Microsoft Entra",
						imageColor: "text-white",
						link: "https://www.microsoft.com/en-us/security/business/microsoft-entra",
						external: true,
					},
					{
						image: Auth0,
						imageAlt: "Auth0",
						imageColor: "text-white",
						link: "https://auth0.com",
						external: true,
					},
					{
						image: JumpCloud,
						imageAlt: "JumpCloud",
						imageColor: "text-white",
						link: "https://jumpcloud.com",
						external: true,
					},
					{
						image: Duo,
						imageAlt: "Duo",
						imageColor: "text-white",
						link: "https://duo.com",
						external: true,
					},
					{
						image: Yubico,
						imageAlt: "Yubico",
						imageColor: "text-white",
						link: "https://yubico.com",
						external: true,
					},
				],
			},
		],

		featureBlocksLower: [
			{
				type: "grid",
				title: "Example Tutorials",
				link: "https://github.com/pritunl/pritunl",
				linkLabel: "Explore Documentation",
				linkIcon: GitHubOutline,
				gridItems: [
					{
						title: "Getting Started",
						description: "Install and configure your first Pritunl VPN server with users, organizations and a running VPN connection.",
						icon: Rocket,
						image: "vpn_getting_started",
						imageNoRing: true,
						imageFit: true,
						link: "https://docs.pritunl.com/kb/vpn/getting-started/installation",
						linkLabel: "View Getting Started Tutorial",
						external: true,
					},
					{
						title: "Replicated Servers",
						description: "Deploy multiple Pritunl hosts for high availability with replicated VPN servers and automatic failover.",
						icon: Copy,
						image: "vpn_replicated_servers",
						imageNoRing: true,
						imageFit: true,
						link: "https://docs.pritunl.com/kb/vpn/tutorials/replicated-servers",
						linkLabel: "View Replicated Servers Tutorial",
						external: true,
					},
					{
						title: "Secure Access to Cloud Network",
						description: "Route VPN client traffic to private cloud resources such as AWS VPCs and other internal networks.",
						icon: Cloud,
						image: "vpn_accessing_private_network",
						imageNoRing: true,
						imageFit: true,
						link: "https://docs.pritunl.com/kb/vpn/tutorials/accessing-a-private-network",
						linkLabel: "View Secure Access to Cloud Network Tutorial",
						external: true,
					},
					{
						title: "Site-to-Site Configuration",
						description: "Connect multiple networks across locations using Pritunl Links for encrypted site-to-site WireGuard or IPsec tunnels.",
						icon: Network,
						image: "vpn_site_to_site",
						imageNoRing: true,
						imageFit: true,
						link: "https://docs.pritunl.com/kb/vpn/tutorials/pritunl-link",
						linkLabel: "View Site-to-Site Configuration Tutorial",
						external: true,
					},
				],
			},
		],

		pricing: {
			title: "Pricing",
			description: "Simple per-host pricing with unlimited users and connections on every plan.",
			plans: [
				{
					name: "Community",
					cost: 0,
					description: "Single server with unlimited users.",
					features: [
						{
							label: "Single server",
							details: "Run a single Pritunl instance",
							icon: Server,
						},
						{
							label: "Unlimited users",
							details: "No limit on the number of users created or users connected",
							icon: Users,
						},
						{
							label: "Unlimited devices",
							details: "No limit on the number of devices that each user has connected",
							icon: Smartphone,
						},
					],
				},
				{
					name: "Premium",
					cost: 10,
					description: "Per-host billing with advanced features.",
					href: "https://buy.stripe.com/aEU4jl8bj9yS7le148",
					external: true,
					buttonLabel: "Subscribe",
					features: [
						{
							label: "Billing per host",
							details: "Each Pritunl host is billed at $10/month. The host can contain an unlimited number of VPN servers and unlimited number of users or connections",
							icon: CreditCard,
						},
						{
							label: "Unlimited users",
							details: "No limit on the number of users created or users connected",
							icon: Users,
						},
						{
							label: "Unlimited devices",
							details: "No limit on the number of devices that each user has connected",
							icon: Smartphone,
						},
						{
							label: "Port forwarding",
							details: "Forward ports to vpn clients",
							icon: ArrowRightLeft,
						},
						{
							label: "Gateway links",
							details: "Create a gateway link to route traffic for a local network to a vpn client. Allowing the vpn clients to access the remote network that is available to the linked vpn client",
							icon: Route,
						},
						{
							label: "Failover gateway links",
							details: "Connect multiple gateway links to a Pritunl server and when a link goes down another available link will automatically be used",
							icon: ShieldCheck,
						},
						{
							label: "Bypass secondary auth",
							details: "Per-user option to bypass secondary authentication such as two-factor authentication. For server users that can't provide a two-factor code",
							icon: KeyRound,
						},
						{
							label: "Chromebook support",
							details: "Easily connect Chromebook users with ChromeOS compatible vpn profiles",
							icon: Laptop,
						},
						{
							label: "Configuration sync",
							details: "When clients connect with a Pritunl client, vpn setting changes such as port/protocol will be updated to allow the client to connect without needing to download a new configuration",
							icon: RefreshCcw,
						},
						{
							label: "Email user keys",
							details: "Email users a link to download vpn profiles using a configured SMTP server",
							icon: Mail,
						},
						{
							label: "Additional themes",
							details: "Change the interface to light or dark theme",
							icon: Palette,
						},
					],
				},
				{
					name: "Enterprise",
					cost: 70,
					description: "All Premium features plus SSO, failover and site-to-site links.",
					featured: true,
					href: "https://buy.stripe.com/00gaHJ4Z7bH0fRKbIV",
					external: true,
					buttonLabel: "Subscribe",
					features: [
						{
							label: "All Premium features",
							details: "All of the features included with a Premium subscription",
							icon: Star,
						},
						{
							label: "Billing per host",
							details: "Each Pritunl host is billed at $70/month. The host can contain an unlimited number of VPN servers and unlimited number of users or connections",
							icon: CreditCard,
						},
						{
							label: "Single sign-on",
							details: "Single sign-on with SAML, Google Apps, Duo Security and Radius",
							icon: LogIn,
						},
						{
							label: "TPM device authentication",
							details: "Device authentication with TPM and Apple Secure Enclave",
							icon: Fingerprint,
						},
						{
							label: "Automatic failover",
							details: "When a Pritunl instance fails the vpn servers running on the instance will automatically failover to another available Pritunl instance",
							icon: HeartPulse,
						},
						{
							label: "Replicated servers",
							details: "Replicate a vpn server across multiple Pritunl instances to easily scale horizontally to handle more user connections",
							icon: Copy,
						},
						{
							label: "VXLan support",
							details: "Automatic VXLan management for replication across availability zones without layer 2 connectivity while still maintaining client-to-client communication",
							icon: Layers,
						},
						{
							label: "AWS VPC integration",
							details: "Integrate with AWS VPC to allow Pritunl to dynamically control the VPC routing table",
							icon: Cloud,
						},
						{
							label: "Site-to-site VPN",
							details: "Easily create a site-to-site link between two Pritunl instances without any complicated configuration",
							icon: Link,
						},
						{
							label: "Server route NAT control",
							details: "Enable or disable NAT for server routes",
							icon: Route,
						},
						{
							label: "DNS mapping",
							details: "Map connected vpn clients to dns domains such as user0.org0.vpn using a custom dns server that runs along with the Pritunl server",
							icon: Globe,
						},
						{
							label: "DNS forwarding",
							details: "Forward dns queries to a dns server on a remote network such as a consul server on an AWS VPC",
							icon: Forward,
						},
						{
							label: "Monitoring",
							details: "Monitor server and user metrics with InfluxDB",
							icon: Activity,
						},
						{
							label: "Advanced auditing",
							details: "Optional advanced auditing of user and administrator related events for improved security and intrusion detection",
							icon: ScrollText,
						},
						{
							label: "Bridged VPN mode",
							details: "Create tap servers that bridge the vpn clients to the servers local network interface. Allowing vpn clients to get an ip address on the servers local network",
							icon: Cable,
						},
						{
							label: "Multiple administrators",
							details: "Allow multiple administrators to manage the Pritunl server",
							icon: UsersRound,
						},
						{
							label: "User pin policy",
							details: "Control over requiring users to set a pin before they are able to connect to a vpn server",
							icon: Lock,
						},
						{
							label: "Plugin system",
							details: "Integrate Pritunl with other systems using plugins written in Python",
							icon: Plug,
						},
						{
							label: "API access",
							details: "Manage Pritunl cluster using RESTful API with support for multiple API keys",
							icon: SquareTerminal,
						},
						{
							label: "IPsec site-to-site links",
							details: "Site-to-site links with IPsec using pritunl-link client. Link client does not require database connection",
							icon: Shield,
						},
						{
							label: "Multi-Cloud VPC peering",
							details: "Simple VPC peering and hybrid cloud with Pritunl link client",
							icon: CloudCog,
						},
						{
							label: "Automated link failover",
							details: "Link failover with automated routing table management and automated port forwarding for Unifi links",
							icon: RefreshCw,
						},
					],
				},
			],
		},

		installTitle: "Installation",
		installDescription: "Select your distribution to view installation instructions.",
		repositories: [
			{ type: "vpn", distro: "arch", version: "", package: "pritunl", mongo: "8.2" },
			{ type: "vpn", distro: "amazon", version: "2023", package: "pritunl", mongo: "8.2" },
			{ type: "vpn", distro: "alma", version: "8", package: "pritunl", mongo: "8.2" },
			{ type: "vpn", distro: "alma", version: "9", package: "pritunl", mongo: "8.2" },
			{ type: "vpn", distro: "alma", version: "10", package: "pritunl", mongo: "8.2" },
			{ type: "vpn", distro: "oracle", version: "8", package: "pritunl", mongo: "8.2" },
			{ type: "vpn", distro: "oracle", version: "9", package: "pritunl", mongo: "8.2" },
			{ type: "vpn", distro: "oracle", version: "10", package: "pritunl", mongo: "8.2" },
			{ type: "vpn", distro: "rocky", version: "8", package: "pritunl", mongo: "8.2" },
			{ type: "vpn", distro: "rocky", version: "9", package: "pritunl", mongo: "8.2" },
			{ type: "vpn", distro: "rocky", version: "10", package: "pritunl", mongo: "8.2" },
			{ type: "vpn", distro: "debian", version: "12", package: "pritunl", mongo: "8.2" },
			{ type: "vpn", distro: "debian", version: "13", package: "pritunl", mongo: "8.2" },
			{ type: "vpn", distro: "ubuntu", version: "20.04", package: "pritunl", mongo: "8.2" },
			{ type: "vpn", distro: "ubuntu", version: "22.04", package: "pritunl", mongo: "8.2" },
			{ type: "vpn", distro: "ubuntu", version: "24.04", package: "pritunl", mongo: "8.2" },
		],

		client: {
			logo: PritunlClient,
			logoAlt: "Pritunl Client",
			title: "OpenVPN and WireGuard Client",
			description: "Free and open source cross platform OpenVPN and WireGuard client. Connect to any OpenVPN server with a secure open source client. Additonal integration available when connecting to a Pritunl server. Free and open source alternative to Viscosity.",
			image: "client_macos",
			imageAlt: "Pritunl Client",
			link: "https://client.pritunl.com",
			linkLabel: "Visit Client Homepage",
			external: true,

			installTitle: "Client Installation",
			installDescription: "Select your distribution to view client installation instructions.",
			repositories: [
				{ distro: "arch", version: "", package: "pritunl-client-electron" },
				{ distro: "alma", version: "10", package: "pritunl-client-electron" },
				{ distro: "oracle", version: "10", package: "pritunl-client-electron" },
				{ distro: "debian", version: "13", package: "pritunl-client-electron" },
				{ distro: "fedora", version: "42", package: "pritunl-client-electron" },
				{ distro: "fedora", version: "43", package: "pritunl-client-electron" },
				{ distro: "ubuntu", version: "24.04", package: "pritunl-client-electron" },
				{ distro: "ubuntu", version: "25.10", package: "pritunl-client-electron" },
			],

			installers: {
				macos: {
					label: "macOS",
					version: "1.3.4562.57",
					url: "https://github.com/pritunl/pritunl-client-electron/releases/download/$version/Pritunl.pkg.zip",
					hashUrl: "https://raw.githubusercontent.com/pritunl/pritunl-client-electron/master/SHA256",
				},
				windows: {
					label: "Windows",
					version: "1.3.4562.57",
					url: "https://github.com/pritunl/pritunl-client-electron/releases/download/$version/Pritunl.exe",
					hashUrl: "https://raw.githubusercontent.com/pritunl/pritunl-client-electron/master/SHA256",
				},
			},
		},

		support: {
			title: "Support",
			description: "Email and community forums available for support. Subscribe to the Substack for security and update announcements.",
			buttons: [
				{ label: "Email Support", link: "https://support.pritunl.com", icon: Mail },
				{ label: "Community Forum", link: "https://forum.pritunl.com", icon: Discourse },
				{ label: "Documentation", link: "https://docs.pritunl.com/kb/vpn", icon: GitBook },
				{ label: "Substack Newsletter", link: "https://pritunl.substack.com/subscribe", icon: Substack },
			],
		},

		footer: {
			icon: Pritunl,
			address1: "1700 7th Ave Ste 116-211",
			address2: "Seattle, WA 98101",
			phone: "(206) 202-2276",
			copyright: `Pritunl, Inc © ${new Date().getFullYear()}`,
			privacy: "https://pritunl.com/privacy",
			terms: "https://pritunl.com/terms",
			twitter: "https://x.com/pritunl",
			bluesky: "https://bsky.app/profile/pritunl.bsky.social",
			github: "https://github.com/pritunl/pritunl",
			linkedin: "https://linkedin.com/company/pritunl",
			substack: "https://pritunl.substack.com",
		},
	},

	pages: {
		home: Home,
		"vpc": {
			title: "Pritunl - Multi-Cloud VPC Peering",
			description: "Free and open source enterprise VPN server with distributed architecture and scalability.",

			badge: "Site-to-Site Multi-Cloud",
			heading: [
				[
					{ text: "Multi-Cloud VPC Peering" },
				],
			],
			subheading: "Interconnect VPC networks using WireGuard or IPsec across AWS, Google Cloud and Oracle Cloud to provide reliable peering with automatic failover that can scale horizontally.",

			buttons: [
				{
					label: "Live Demo",
					href: "https://demo.pritunl.com",
					style: "secondary",
					external: true,
				},
				{
					label: "Get Started",
					href: "https://docs.pritunl.com/kb/vpn/sso/connection-authentication",
					style: "primary",
					external: true,
				},
			],

			featureBlocks: [
				{
					type: "right",
					title: "Reliable VPC Networking",
					description: "Interconnect your VPC networks and provide remote access in minutes. Pritunl can handle both small and large use cases on AWS without any complicated configuration.",
					image: "vpn_infrastructure",
					imageAlt: "High Availability Infrastructure",
					imageNoRing: true,
					items: [
						{
							icon: Shield,
							title: "WireGuard and IPsec Links",
							description: "Create high performance site-to-site links between datacenters and cloud networks using WireGuard and IPsec with support for both hub-and-spoke and mesh topologies.",
						},
						{
							icon: RefreshCw,
							title: "Automated Failover",
							description: "Automatically update cloud provider routing tables using native APIs when a link failure is detected, ensuring traffic is rerouted to a healthy node with no manual intervention.",
						},
						{
							icon: Globe,
							title: "Multi-Cloud Connectivity",
							description: "Link networks across AWS, Google Cloud, Azure, Oracle Cloud, Pritunl Cloud, Hetzner and on-premise datacenters from a single management interface with unified routing and monitoring.",
						},
					],
				},
				{
					type: "grid",
					title: "Supported Link Providers",
					link: "https://docs.pritunl.com/kb/vpn/link",
					linkLabel: "Explore VPN Link Documentation",
					linkIcon: Network,
					gridItems: [
						{
							title: "Amazon AWS",
							description: "Create site-to-site VPN links between Pritunl servers and AWS VPC networks.",
							image: AmazonAws,
							imageAlt: "Amazon AWS",
							imageColor: "text-white",
							imageNoRing: true,
							imageFit: true,
							imageBox: "p-5 h-30",
							link: "https://docs.pritunl.com/kb/vpn/link/aws",
							linkLabel: "View AWS Documentation",
							external: true,
						},
						{
							title: "Google Cloud",
							description: "Establish VPN links between Pritunl servers and Google Cloud VPC networks.",
							image: GoogleCloud,
							imageAlt: "Google Cloud",
							imageColor: "text-white",
							imageNoRing: true,
							imageFit: true,
							imageBox: "p-5 h-30",
							link: "https://docs.pritunl.com/kb/vpn/link/google-cloud",
							linkLabel: "View Google Cloud Documentation",
							external: true,
						},
						{
							title: "Microsoft Azure",
							description: "Connect Pritunl servers to Azure virtual networks with site-to-site VPN links.",
							image: MicrosoftAzure,
							imageAlt: "Microsoft Azure",
							imageNoRing: true,
							imageFit: true,
							imageBox: "p-5 h-30",
							link: "https://docs.pritunl.com/kb/vpn/link/azure-link",
							linkLabel: "View Azure Documentation",
							external: true,
						},
						{
							title: "Oracle Cloud",
							description: "Link Pritunl servers to Oracle Cloud Infrastructure virtual cloud networks.",
							image: Oracle,
							imageAlt: "Oracle Cloud",
							imageColor: "text-[#f80102]",
							imageNoRing: true,
							imageFit: true,
							imageBox: "p-5 h-30",
							link: "https://docs.pritunl.com/kb/vpn/link/oracle-cloud",
							linkLabel: "View Oracle Cloud Documentation",
							external: true,
						},
						{
							title: "Pritunl Cloud",
							description: "Deploy VPN links natively within the Pritunl Cloud virtualization platform.",
							image: PritunlCloud,
							imageAlt: "Pritunl Cloud",
							imageColor: "text-white",
							imageNoRing: true,
							imageFit: true,
							imageBox: "p-5 h-30",
							link: "https://docs.pritunl.com/kb/cloud",
							linkLabel: "View Pritunl Cloud Documentation",
							external: true,
						},
						{
							title: "Hetzner",
							description: "Build site-to-site VPN links between Pritunl servers and Hetzner Cloud networks.",
							image: Hetzner,
							imageAlt: "Hetzner",
							imageColor: "text-[#d50c2d]",
							imageNoRing: true,
							imageFit: true,
							imageBox: "p-5 h-30",
							link: "https://docs.pritunl.com/kb/vpn/link",
							linkLabel: "View Hetzner Documentation",
							external: true,
						},
					],
				},
				{
					type: "grid",
					title: "Dynamic DNS",
					description: "Automatically manage DNS records for connected VPN users and forward queries to remote networks.",
					gridItems: [
						{
							icon: AtSign,
							title: "DNS Mapping",
							description: "All connected users and devices are automatically mapped to a DNS domain using their username and organization name, such as user0.organization0.vpn.",
						},
						{
							icon: Route,
							title: "DNS Forwarding",
							description: "Forward DNS queries to a DNS server on a remote network such as a Consul server on an AWS VPC. Map user domains to internal services, for example search.user.org.vpn resolves to search.node.consul.",
						},
					],
				},
			],
		},
		"sso": {
			title: "Pritunl - Single Sign On",
			description: "Free and open source enterprise VPN server with distributed architecture and scalability.",

			badge: "Secure Single Sign On VPN",
			heading: [
				[
					{ text: "Pritunl " },
					{ text: "Server", highlight: true },
					{ text: " Single Sign On" },
				],
			],
			subheading: "Securely deploy remote access to thousands of users using their existing company account with support for several single sign-on providers and protocols.",

			buttons: [
				{
					label: "Live Demo",
					href: "https://demo.pritunl.com",
					style: "secondary",
					external: true,
				},
				{
					label: "Get Started",
					href: "https://docs.pritunl.com/kb/vpn/sso/connection-authentication",
					style: "primary",
					external: true,
				},
			],

			featureBlocks: [
				{
					type: "grid",
					title: "Single Sign On Providers",
					link: "https://docs.pritunl.com/kb/vpn/sso/connection-authentication",
					linkLabel: "Explore Single Sign-On Documentation",
					linkIcon: IdCard,
					gridItems: [
						{
							title: "Google Workspace",
							description: "Authenticate VPN users with Google Workspace accounts using OAuth single sign-on.",
							image: GoogleWorkspace,
							imageAlt: "Google Workspace",
							imageColor: "text-white",
							imageNoRing: true,
							imageFit: true,
							imageBox: "p-5 h-30",
							link: "https://docs.pritunl.com/kb/vpn/sso/google",
							linkLabel: "View Google Workspace Documentation",
							external: true,
						},
						{
							title: "Okta",
							description: "Integrate Okta identity management for SAML-based VPN authentication. Multi factor supported with Okta Verify app.",
							image: Okta,
							imageAlt: "Okta",
							imageColor: "text-white",
							imageNoRing: true,
							imageFit: true,
							imageBox: "p-5 h-30",
							link: "https://docs.pritunl.com/kb/vpn/sso/okta",
							linkLabel: "View Okta Documentation",
							external: true,
						},
						{
							title: "OneLogin",
							description: "Connect OneLogin for centralized SAML single sign-on to your VPN servers. Multi factor supported with OneLogin Protect app.",
							image: OneLogin,
							imageAlt: "OneLogin",
							imageColor: "text-white",
							imageNoRing: true,
							imageFit: true,
							imageBox: "p-5 h-30",
							link: "https://docs.pritunl.com/kb/vpn/sso/onelogin",
							linkLabel: "View OneLogin Documentation",
							external: true,
						},
						{
							title: "Microsoft Entra",
							description: "Enable VPN authentication with Microsoft Entra ID using SAML or Azure AD integration.",
							image: MicrosoftEntra,
							imageAlt: "Microsoft Entra",
							imageColor: "text-white",
							imageNoRing: true,
							imageFit: true,
							imageBox: "p-5 h-30",
							link: "https://docs.pritunl.com/kb/vpn/sso/azure",
							linkLabel: "View Microsoft Entra Documentation",
							external: true,
						},
						{
							title: "Auth0",
							description: "Configure Auth0 as an identity provider for flexible VPN single sign-on.",
							image: Auth0,
							imageAlt: "Auth0",
							imageColor: "text-white",
							imageNoRing: true,
							imageFit: true,
							imageBox: "p-5 h-30",
							link: "https://docs.pritunl.com/kb/vpn/sso/auth0",
							linkLabel: "View Auth0 Documentation",
							external: true,
						},
						{
							title: "JumpCloud",
							description: "Integrate JumpCloud directory for SAML-based VPN user authentication.",
							image: JumpCloud,
							imageAlt: "JumpCloud",
							imageColor: "text-white",
							imageNoRing: true,
							imageFit: true,
							imageBox: "p-5 h-30",
							link: "https://docs.pritunl.com/kb/vpn/sso/jumpcloud",
							linkLabel: "View JumpCloud Documentation",
							external: true,
						},
						{
							title: "Duo Security",
							description: "Add Duo push-based multi-factor authentication to VPN connections.",
							image: Duo,
							imageAlt: "Duo",
							imageColor: "text-white",
							imageNoRing: true,
							imageFit: true,
							imageBox: "p-5 h-30",
							link: "https://docs.pritunl.com/kb/vpn/sso/duo",
							linkLabel: "View Duo Security Documentation",
							external: true,
						},
						{
							title: "YubiKey",
							description: "Require YubiKey hardware token verification for VPN authentication.",
							image: Yubico,
							imageAlt: "Yubico",
							imageColor: "text-white",
							imageNoRing: true,
							imageFit: true,
							imageBox: "p-5 h-30",
							link: "https://docs.pritunl.com/kb/vpn/sso/yubikey",
							linkLabel: "View YubiKey Documentation",
							external: true,
						},
						{
							title: "Slack",
							description: "Authenticate VPN users with Slack workspace accounts using OAuth single sign-on.",
							image: Slack,
							imageAlt: "Slack",
							imageColor: "text-white",
							imageNoRing: true,
							imageFit: true,
							imageBox: "p-5 h-30",
							link: "https://docs.pritunl.com/kb/vpn/sso/slack",
							linkLabel: "View Slack Documentation",
							external: true,
						},
					],
				},
				{
					type: "grid",
					title: "Custom Authentication",
					description: "Custom single sign-on authentication configurations are also available.",
					gridItems: [
						{
							title: "RADIUS",
							description: "Authenticate VPN users against a RADIUS server for centralized credential management.",
							image: FreeRadius,
							imageAlt: "FreeRADIUS",
							imageColor: "text-white",
							imageNoRing: true,
							imageFit: true,
							imageBox: "p-5 h-30",
							link: "https://docs.pritunl.com/kb/vpn/sso/active-directory",
							linkLabel: "View RADIUS Documentation",
							external: true,
						},
						{
							title: "Custom Plugin",
							description: "Build custom authentication logic with a Python-based plugin system.",
							image: PritunlDev,
							imageAlt: "Pritunl Plugin",
							imageColor: "text-white",
							imageNoRing: true,
							imageFit: true,
							imageBox: "p-5 h-30",
							link: "https://docs.pritunl.com/kb/vpn/system/plugins",
							linkLabel: "View Plugin Documentation",
							external: true,
						},
						{
							title: "Windows Active Directory",
							description: "Authenticate VPN users against a local Active Directory domain using RADIUS integration.",
							image: Windows,
							imageAlt: "Windows",
							imageColor: "text-white",
							imageNoRing: true,
							imageFit: true,
							imageBox: "p-5 h-30",
							link: "https://docs.pritunl.com/kb/vpn/sso/active-directory",
							linkLabel: "View Active Directory Documentation",
							external: true,
						},
					],
				},
			],
		},
		"infrastructure": {
			title: "Pritunl - Distributed and Scalable Infrastructure",
			description: "Quickly scale to thousands of users with high availability in a cloud environment without the need for expensive proprietary hardware.",

			badge: "Scalable Infrastructure",
			heading: [
				[
					{ text: "Distributed and Scalable " },
					{ text: "Infrastructure", highlight: true },
				],
			],
			subheading: "Quickly scale to thousands of users with high availability in a cloud environment without the need for expensive proprietary hardware.",

			buttons: [
				{
					label: "Live Demo",
					href: "https://demo.pritunl.com",
					style: "secondary",
					external: true,
				},
				{
					label: "Learn More",
					href: "https://docs.pritunl.com/kb/vpn/system/infrastructure",
					style: "primary",
					external: true,
				},
			],

			heroImage: {
				image: "vpn_servers",
				alt: "Pritunl Distributed Infrastructure",
				ring: false,
				noBorder: true,
				small: true,
			},

			featureBlocks: [
				{
					type: "grid",
					title: "Reliable Infrastructure",
					link: "https://docs.pritunl.com/kb/vpn/system/infrastructure",
					linkLabel: "View Infrastructure Documentation",
					linkIcon: Server,
					gridItems: [
						{
							icon: DatabaseBackup,
							title: "Replication and High Availability",
							description: "All servers operate as equal peers with no single point of failure. When an instance fails, connected clients are automatically routed to a healthy node with no manual intervention required.",
							link: "https://medium.com/@pritunl/pritunl-20k-clients-e990a399e954",
							linkIcon: FlaskConical,
							linkLabel: "View 20k Concurrent Clients Test",
						},
						{
							icon: Scaling,
							title: "Scale Complex Configurations",
							description: "Deploy complex multi-server topologies and site-to-site network links with minimal configuration. Redundant link design ensures failover without unexpected outages.",
							link: "https://docs.pritunl.com/kb/vpn/system/scaling",
							linkIcon: BookOpen,
							linkLabel: "Explore Scaling Documentation",
						},
					],
				},
			],
		},
	},
}

export default definition
